name: analytix
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/app
    volumes:
      - ./storage:/var/www/app/storage
      - ./bootstrap/cache:/var/www/app/bootstrap/cache
      - ./.env:/var/www/app/.env
      - composer_cache:/var/www/.cache/composer
      - npm_cache:/var/www/.npm
    networks:
      - analytix-network

  nginx:
    image: nginx:alpine
    container_name: analytix-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-9999}:80"
    volumes:
      - ./:/var/www/app:ro
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - analytix-network
    depends_on:
      - app

networks:
  analytix-network:
    driver: bridge

volumes:
  composer_cache:
  npm_cache:
