name: analytix
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: analytix
    container_name: analytix-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - analytix-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: analytix-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - analytix-network

networks:
  analytix-network:
    driver: bridge
