name: analytix
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - analytix-network

  nginx:
    image: nginx:alpine
    container_name: analytix-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - analytix-network
    depends_on:
      - app

networks:
  analytix-network:
    driver: bridge
